# Generated by Django 3.2.25 on 2024-08-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('first_name_ar', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('family_name_ar', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_ar', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Entity', 'Entity')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('marketing_referral', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('title_ar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activation_date', models.DateField()),
                ('renewal_duration', models.IntegerField()),
                ('renewal_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('SAR', 'SAR')], max_length=10)),
                ('manager', models.CharField(max_length=255)),
                ('accrued_type', models.CharField(choices=[('start_of_day', 'Start of Day'), ('end_of_day', 'End of Day'), ('end_of_day_with_holidays', 'End of Day with Holidays')], max_length=50)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('value_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('benchmark', models.CharField(max_length=255)),
                ('frequency_closed', models.CharField(max_length=50)),
                ('next_close_date', models.DateField()),
                ('type_weight', models.CharField(choices=[('total_weight', 'Total Weight'), ('net_weight', 'Net Weight')], max_length=50)),
                ('fixed_fees_fist', models.BooleanField()),
                ('avr_to_market', models.BooleanField()),
                ('calc_daily_with_holiday', models.BooleanField()),
                ('funding_type', models.CharField(choices=[('cash_financing', 'Cash Financing'), ('murabaha', 'Murabaha'), ('no_financing', 'No Financing'), ('all_financing', 'All Financing')], max_length=50)),
                ('portfolio_management_type', models.CharField(choices=[('managed', 'Managed'), ('advised', 'Advised')], max_length=50)),
                ('included_in_main', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('bank_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.bankbranch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.investmenttype')),
                ('main_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.portfolio')),
                ('profile_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.portfoliostock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.clientnature'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_management.clienttype'),
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_management.clienttitle'),
        ),
    ]
