# Generated by Django 3.2.25 on 2024-08-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('client_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_order', models.DateField()),
                ('broker', models.CharField(max_length=255)),
                ('dealer', models.CharField(max_length=255)),
                ('bkeeper', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('type_order', models.CharField(max_length=50)),
                ('price_marketing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_deal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_is', models.BooleanField(default=False)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_same', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('executed_qty', models.IntegerField(default=0)),
                ('value_order', models.DecimalField(decimal_places=2, max_digits=15)),
                ('factor_safety', models.DecimalField(decimal_places=2, max_digits=5)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
