# Generated by Django 3.2.25 on 2024-08-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('instruments', '0001_initial'),
        ('orders', '0002_auto_20240806_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('broker_name', models.CharField(max_length=255)),
                ('stock_name', models.CharField(max_length=255)),
                ('executor_name', models.CharField(max_length=255)),
                ('operation_type', models.CharField(choices=[('buy', 'شراء'), ('sell', 'بيع')], max_length=10)),
                ('order_date', models.DateField()),
                ('requested_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_requested_quantity', models.IntegerField()),
                ('broker_invoice_number', models.CharField(max_length=100)),
                ('executed_quantity', models.IntegerField()),
                ('execution_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conversion_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('execution_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_execution_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=20)),
                ('execution_value', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionRedemptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('custodian', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('ADDITION', 'Addition'), ('REDEMPTION', 'Redemption')], max_length=10)),
                ('capital_effect', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.stock')),
            ],
        ),
    ]
