# Generated by Django 3.2.25 on 2024-08-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('orders', '0003_additionredemptionorder_execution_registeredowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('coupon_no', models.CharField(max_length=50)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plus_day', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.stock')),
            ],
        ),
    ]
