# Generated by Django 3.2.25 on 2024-08-28 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('client_management', '0001_initial'),
        ('orders', '0004_cashdividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDividendDiscounted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_type', models.CharField(choices=[('FREE', 'Free Stock'), ('DISCOUNTED', 'Discounted Stock')], max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.bank')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.bankbranch')),
                ('dividend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cashdividend')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CashDividendOpeningBalance',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateField()),
                ('coupon_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('div_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('bkeeper', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cash_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.client')),
                ('div_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cashdividend')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.stock')),
            ],
        ),
    ]
